### PR TITLE
Makefile: honor CPPFLAGS as well for correct hardening.

### PR DESCRIPTION
**Pull request by cdluminate**

### CODE REVIEW

**Comment by adsr** [comment]
Is something like this a valid alternative?

```diff
diff --git a/debian/rules b/debian/rules
index d704428..85e99d1 100755
--- a/debian/rules
+++ b/debian/rules
@@ -2,6 +2,11 @@
 
 export DEB_BUILD_MAINT_OPTIONS=hardening=+all
 
+DPKG_EXPORT_BUILDFLAGS = 1
+include /usr/share/dpkg/buildflags.mk
+
+CFLAGS += $(CPPFLAGS)
+
 %:
 	dh $@
 
```

Also, is there a different Lintian config I should be using that will emit the warnings you pointed out [here](https://github.com/adsr/mle/issues/79#issuecomment-1595954375)? This is the most verbose I can get it on my system:

```
test@debian:/tmp/mle.QgNxRcWtww$ lintian -I -E --pedantic mle_1.7.2-1_source.changes
X: mle source: debian-watch-does-not-check-gpg-signature
P: mle source: package-uses-old-debhelper-compat-version 10
P: mle source: silent-on-rules-requiring-root
X: mle source: upstream-metadata-file-is-missing
```

**Comment by cdluminate** [comment]
I usually use `lintian -EviI` without the `--pedantic` option. The alternative is acceptable as long as it works.

**Comment by cdluminate** [comment]
BTW, CPPFLAGS is C-Pre-Processor flags, instead of C-Plus-Plus flags. So I think it should be there in the makefile.

**Comment by adsr** [comment]
Thank you for the reminder about `CPPFLAGS`. I often confuse it for `CXXFLAGS`.

**Pull request merged**
